### ISSUE TITLE
Do not import whole semantic-ui-react

### ISSUE THREAD

**Issue by amaury1093** [paritytech/js-ui#5]
It's quite common for dapps to do `import Button from '@parity/ui/lib/Button';`

Looking at the code, this Button.js contains:

`import { Button as SemanticButton } from 'semantic-ui-react';`

This imports the whole semantic-ui-react package into the build, even if the dapp only uses a Button.

It would be wiser to use:

`import SemanticButton from 'semantic-ui-react/dist/commonjs/elements/Button';`

**Comment by jacogr** [comment]
+1 Good optimisation.
